spring:
  application:
    name: order-service  # the same with com.yiqiniu.easytrans.demos.order.Constant.APPID
  datasource: # order service datasource config
    url: jdbc:postgresql://localhost:5432/easytx_order
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

server:
  port: 18080

# RIBBON用，也可以直接开启Eureka
order-service:
  ribbon:
    listOfServers: localhost:18080

wallet-service:
  ribbon:
    listOfServers: localhost:18081

easytrans:
  master:
    zk:
      zooKeeperUrl: localhost:2281
  stringcodec:
    zk:
      zooKeeperUrl: ${easytrans.master.zk.zooKeeperUrl}
  idgen:
    trxId:
      zkSnow:
        zooKeeperUrl: ${easytrans.master.zk.zooKeeperUrl}
  log:
    database:
      logCleanEnabled: true
      logReservedDays: 14
      logCleanTime: 01:22:00
      druid:
        driverClassName: com.mysql.jdbc.Driver
        url: jdbc:mysql://localhost:3306/easytx_order_translog?characterEncoding=UTF-8&useSSL=false
        username: root
        password: root


debug: true

    
      